---
- name: Deploy PHP Application
  hosts: testserver
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add root to Docker group
      user:
        name: root
        groups: docker
        append: yes

    - name: Enable Docker Service
      systemd:
        name: docker
        enabled: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started

    - name: Pull Docker Image
      docker_image:
        name: frawatson/edureka_cert
        source: pull

    - name: Start Docker Container
      docker_container:
        name: edureka_cert_stack
        image: frawatson/edureka_cert
        ports:
          - "80:80"
        volumes:
          - /path/to/local/html:/var/www/html
        restart_policy: always
