---
- name: Deploy PHP Application
  hosts: testserver
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        
    - name: Install Docker
      apt:
        name: docker-compose
        state: present

    - name: Add root to Docker group
      user:
        name: root
        groups: docker
        append: yes

    - name: Enable Docker Service
      systemd:
        name: docker
        enabled: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
