---
- name: Deploy PHP Application
  hosts: testserver
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker Image
      docker_image:
        name: frawatson/edureka_cert
        source: pull

    - name: Start Docker Service
      docker_container:
        name: edureka_cert_stack
        image: frawatson/edureka_cert
        ports:
          - "80:80"
        volumes:
          - :/var/www/html
        restart_policy: always
